// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptOffer(arg1, arg2) {
  return window['go']['main']['App']['AcceptOffer'](arg1, arg2);
}

export function AutoAcceptOffer(arg1, arg2) {
  return window['go']['main']['App']['AutoAcceptOffer'](arg1, arg2);
}

export function GetLocalDevice() {
  return window['go']['main']['App']['GetLocalDevice']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function RejectOffer(arg1) {
  return window['go']['main']['App']['RejectOffer'](arg1);
}

export function SendFile(arg1, arg2) {
  return window['go']['main']['App']['SendFile'](arg1, arg2);
}
