// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function AcceptOffer(arg1:string):Promise<void>;

export function AddTrustedDevice(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearHistory():Promise<void>;

export function GetAliases():Promise<Record<string, string>>;

export function GetAppVersion():Promise<string>;

export function GetHistory():Promise<Array<models.HistoryEntry>>;

export function GetLastSeenVersion():Promise<string>;

export function GetLocalDevice():Promise<models.Peer>;

export function GetPeers():Promise<Array<models.Peer>>;

export function OpenDownloadFolder():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RejectOffer(arg1:string):Promise<void>;

export function SaveLastSeenVersion(arg1:string):Promise<void>;

export function SendFile(arg1:string,arg2:number):Promise<void>;

export function SetAlias(arg1:string,arg2:string):Promise<void>;
