// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AcceptOffer(arg1:string,arg2:string):Promise<void>;

export function GetLocalDevice():Promise<models.Peer>;

export function GetPeers():Promise<Array<models.Peer>>;

export function RejectOffer(arg1:string):Promise<void>;

export function SendFile(arg1:string,arg2:number):Promise<void>;
